export { default as SignUp } from './SignUp';
export { default as SignIn } from './SignIn';
export { default as Home } from './Home';
export { default as Projects } from  './Projects';
export { default as SingleProject } from './SingleProject';
export { default as Profile } from './Profile';
export { default as CreateProject } from './CreateProject';
export { default as Admin } from './Admin';
export { default as DonateHistoryPage } from './DonateHistory';